### ISSUE TITLE
AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'create_pipe_connection'

### ISSUE THREAD

**Issue by imsang27** [GayPizzaSpecifications/stable-diffusion-rpc#1]
Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py

Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 34, in on_ui_tabs
        start_rpc()
      File "C:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 27, in start_rpc
        rpc.connect()
      File "C:\stable-diffusion-webui\venv\lib\site-packages\pypresence\presence.py", line 43, in connect
        self.loop.run_until_complete(self.handshake())
      File "C:\Users\imsan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
        return future.result()
      File "C:\stable-diffusion-webui\venv\lib\site-packages\pypresence\baseclient.py", line 116, in handshake
        self.sock_writer, _ = await asyncio.wait_for(self.loop.create_pipe_connection(lambda: reader_protocol, ipc_path), self.connection_timeout)
    AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'create_pipe_connection'

How do I solve this problem?

**Comment by azenla** [comment]
Wrong repo?
